### ISSUE TITLE
GVSU R Studio Server link not working

### ISSUE THREAD

**Issue by a-duimstra** [STA518-01-SS21/community#19]
Not sure if anyone else is having this problem, but whenever I click on the GVSU R Studio Server link in Blackboard or try to go back to my R projects, I get this page:

![image](https://user-images.githubusercontent.com/83919494/119028597-a5dd7b80-b975-11eb-87dc-b23af6d2ee7c.png)

**Comment by dykesb** [comment]
Please contact HPC technical support: https://www.gvsu.edu/hpc/contact-4.htm

**Comment by a-duimstra** [comment]
Thanks, they just helped me fix it!

**Comment by allysonoco** [comment]
Do you know what they did to fix the issue? I am unable to open RStudio as well and the tech support is not open on the weekends.

**Comment by a-duimstra** [comment]
@allysonoco I honestly have no clue, I emailed them what the problem was and they said they fixed something on their end. They told me to try clearing my history or trying a different browser at first, so maybe try that?

**Comment by a-duimstra** [comment]
@allysonoco I was able to get to RStudio on STRATUS to temporarily work on the assignment, it was just a little different.

**Comment by dykesb** [comment]
@a-duimstra did the STRATUS RStudio connect to GitHub? I know this has been a pain point in the past which is why I do not usually recommend this alternate route.

**Comment by BenBurkholder** [comment]
I was also having issues and this worked for me.

Instructions
When prompted with “error occurred during transmission”

- Clear your web browser’s caches
- Go to rstudio.hpc.gvsu.edu/home in your Web Browser
- Make sure you’re using the “/home” in the URL otherwise you will not see the same items as shown in the following steps.
- If prompted, log in
- If there are active sessions, choose the Quit All option at the top of the page to quit them
- Check the box to Force Quit and click the Quit Session button
- Click New Session
- Rstudio Home page with an arrow pointing to the New Session Button
- You should now have a new Rstudio Session

**Comment by a-duimstra** [comment]
@dykesb it did connect to GitHub, it was just really slow and crashed a few times - the way we normally do it definitely works better

**Comment by allysonoco** [comment]
@BenBurkholder Thank you! That worked!

**Comment by KMiedema** [comment]
I also can not access the RStudio server. I was mainly getting the error that @BenBurkholder mentioned, so I tried his method to fix it and it still didn't work. Tried multiple browsers and even a different device and now I'm getting a mix of errors that will either say "error occurred during transmission" or "failed to initialize".
