### ISSUE TITLE
Activity 10.1 For loop

### ISSUE THREAD

**Issue by katiewebster** [STA518-01-SS21/community#36]
I'm having an issue figuring out the for loop to read all of the urls and to store them and add them onto the tibble we created called tmdb_for_loop. I successfully created the tibble, have a functioning function called scrape_tmdb and have been trying something like this:

```{r}
for (i in names(tmdb_tv_urls)) {
  scraped <- scrape_tmdb(tmdb_tv_urls[[i]])
  # tmdb_for_loop[[i]] <- rbind(scraped, scraped + 1)
}
```

I just have no idea where to go with this and have been Googling for hours.

**Comment by dykesb** [comment]
Somethings to be aware of:

1. `names(tmdb_tv_urls)` returns the column names of `tmdb_tv_url` so this is probably just one item. I do not think you need the `names` function.
2. If you only have `tmbd_tv_urls` in your for loop definition (i.e., `i in tmdb_tv_urls`), `i` then represents each item in this vector. So using `tmdb_tv_url[[i]]` will not work because square brackets are used for indexing (i.e., the item's number in the vector). You'd either need your for loop definition to be on indices (1 through the length of the vector) or use `scrape_tmdb(i)`.
3. For the rbind portion, for loops only work on the current iteration so you can't tell it to look ahead with `+ 1`. You can, however, have it add to what already exists. That is, `tmdb_for_loop <- rbind(tmdb_for_loop, scraped)`.

**Comment by katiewebster** [comment]
> Somethings to be aware of:
> 
> 1. `names(tmdb_tv_urls)` returns the column names of `tmdb_tv_url` so this is probably just one item. I do not think you need the `names` function.
> 2. If you only have `tmbd_tv_urls` in your for loop definition (i.e., `i in tmdb_tv_urls`), `i` then represents each item in this vector. So using `tmdb_tv_url[[i]]` will not work because square brackets are used for indexing (i.e., the item's number in the vector). You'd either need your for loop definition to be on indices (1 through the length of the vector) or use `scrape_tmdb(i)`.
> 3. For the rbind portion, for loops only work on the current iteration so you can't tell it to look ahead with `+ 1`. You can, however, have it add to what already exists. That is, `tmdb_for_loop <- rbind(tmdb_for_loop, scraped)`.

Thank you! This helped and I now have a working for loop.
