### ISSUE TITLE
Error: Unable to discover a GitHub personal access token (Preparation 2)

### ISSUE THREAD

**Issue by poirieca** [STA518-01-SS21/community#7]
Got this error at the end of Task 4 when submitting the use_github() 

"Error: Unable to discover a GitHub personal access token
A token is required in order to create and push to a new repo

Call `gh_token_help()` for help configuring a token"

**Comment by tkishbaugh** [comment]
I initially received the same error message, so I started over and created a new PAT. Now I get the following error after entering ```use_github()```

```
Error in validate_gh_pat(new_gh_pat(x)) : 
  A GitHub PAT must consist of 40 hexadecimal digits
```

However, my PAT appears to contain 40 characters

**Comment by begaliyk** [comment]
> I initially received the same error message, so I started over and created a new PAT. Now I get the following error after entering `use_github()`
> 
> ```
> Error in validate_gh_pat(new_gh_pat(x)) : 
>   A GitHub PAT must consist of 40 hexadecimal digits
> ```
> 
> However, my PAT appears to contain 40 characters

I did exactly the same thing as well and have the same error message now. Still haven't figured it out.

**Comment by dykesb** [comment]
Let's try a different method (the GitHub first).

## ☑️ Task 1

1. In GitHub, click on the ➕ in the upper-right corner (next to your profile picture) and select *New repository*.
2. On the **Create a new repository** page, name your repo `preparation02`, verify that you are creating a *Public* repo, then click on **Create repository**.
3. On the **preparation02** page, click on the green **Code** button, verify that you have the *HTTPS* link, and copy the link provide.
4. In RStudio Server, delete your current `preparation02` directory
    - Click on the big blue R (upper-left corner), quit all sessions, start a new session
    - In the **Files** pane (lower-right pane), navigate to the `preparation02` folder previous created (do not go into the folder) 
    - Check the box next to it, click on **Delete** in this pane's tool bar
    - Click **Yes** on the Confirm Delete pop-up
5. Create a new project, but this time create a **Version Control** Project (instead of New Directory as instructed in Preparation 2).
6. Select **Git** for your Version Control option
7. Paste your repo's HTTPS link previously copied (step 3) in the *Repository URL* box, verify that the *Project directory name* box auto-filled (if not, click on this box and press Command - this is usually a Mac issue; silly Macs) and navigate to the area you want to save to by clicking on **Browse**. Then, click on **Create Project**.

## ☑️ Task 2

Do as stated again to verify that your git configuration information is still saved (should be).

## ☑️ Task 3

Make some changes as stated.

## ☑️ Task 4

In the **Git** pane, click on the green up arrow (push) on the pane toolbar. You should be asked to login with your GitHub username and a password. For your password, provide your PAT.

If this does not work, I might have a **Plan C** 😃

**Comment by tkishbaugh** [comment]
Thanks, @dykesb! I was able to create the repository using the GitHub first method.

**Comment by kruskies** [comment]
I am having issues with this version of the tasks as well. In the **git** panel, none of the files appeared for me to **commit** them.

The green up arrow is also not available to be clicked on.

**Comment by dykesb** [comment]
Did you create a new R script and save it within your `preparation02` RStudio Project folder (at the same folder level as the `preparation02.Rproj` file; this is the old Task 3)?

**Comment by kruskies** [comment]
Yes, it shows that the preparation02-file is contained within preparation02 folder.
![image](https://user-images.githubusercontent.com/83828474/117878146-6c20bc80-b273-11eb-94f3-edf31c329e2f.png)

**Comment by dykesb** [comment]
Try adding another calculation (e.g., `4 * 3`) to your R script, then save to see if Git will recognize that you made a change.

**Comment by kruskies** [comment]
I have done that as well and nothing pops up in the Git window even upon manually refreshing the tab

**Comment by kruskies** [comment]
I think I finally got everything to work after approximately five attempts! Thank you!

**Comment by dykesb** [comment]
Could you provide a summary of what you did to resolve this? This will help your peers (and me for future semesters).

**Comment by kruskies** [comment]
Honestly, I'm not even sure why it happened to work this time. I just kept following the steps listed above and when they didn't work out, I started over.

**Comment by katiewebster** [comment]
I now did this GitHub First method but I accidentally logged in using my GitHub password instead of using the PAT as my password. Did this change anything? I still see the files in my new preparation02 repository.

**Comment by dykesb** [comment]
There could be something that changed, but it really depends on when you supplied your password instead of PAT - e.g., when first cloning, when pushing, when creating a branch.

Aside, I hope to find a way to store the credentials so you do not need to keep entering your PAT as your password for our session on 5/17.
